	class SSV_Unit_Vanguard_J13;
    
    class SSV_Unit_Vanguard_J13_Expeditionary: SSV_Unit_Vanguard_J13
	{
		_generalMacro="SSV_Unit_Vanguard_J13_Expeditionary";
		displayName = "Expeditionary (Assault)";
		uniformClass="SSV_Uniform_Vanguard_J13_Expeditionary";
		optic="optic_Hamr";
        faction = "SSV_Aux_Vanguard_SpecOps";
		linkedItems[]=
		{
			"SSV_Helmet_Vanguard_Pilot_Expeditionary",
			"SSV_Vest_Vanguard_SMG_Expeditionary",
			"Balaclava_Black_EPSM",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"SSV_Helmet_Vanguard_Pilot_Expeditionary",
			"SSV_Vest_Vanguard_SMG_Expeditionary",
			"Balaclava_Black_EPSM",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"JMSJEFF_IMRRifle",
			"SSV_Weapon_Vanguard_Expeditionary_Revolver",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"JMSJEFF_IMRRifle",
			"SSV_Weapon_Vanguard_Expeditionary_Revolver",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"JMSJEFF_30Rnd_IMR_mag",
			"JMSJEFF_30Rnd_IMR_mag",
			"JMSJEFF_30Rnd_IMR_mag",
			"JMSJEFF_30Rnd_IMR_mag",
			"JMSJEFF_30Rnd_IMR_mag",
			"JMSJEFF_30Rnd_IMR_mag",
			"WRS_Revolver_Magazine",
			"WRS_Revolver_Magazine",
			"SSV_Vanguard_Mag_OrganicGrenade",
			"SSV_Vanguard_Mag_OrganicGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"JMSJEFF_30Rnd_IMR_mag",
			"JMSJEFF_30Rnd_IMR_mag",
			"JMSJEFF_30Rnd_IMR_mag",
			"JMSJEFF_30Rnd_IMR_mag",
			"JMSJEFF_30Rnd_IMR_mag",
			"JMSJEFF_30Rnd_IMR_mag",
			"WRS_Revolver_Magazine",
			"WRS_Revolver_Magazine",
			"SSV_Vanguard_Mag_OrganicGrenade",
			"SSV_Vanguard_Mag_OrganicGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		hiddenSelectionsTextures[] =
		{
			"SSV_Vanguard\textures\j13\helldiver\j13_1_co.paa",
			"SSV_Vanguard\textures\j13\helldiver\j13_2_co.paa",
			"SSV_Vanguard\textures\j13\helldiver\j13_3_co.paa"
		};
        hiddenSelectionsMaterials[] =
        {
            "SSV_Vanguard\textures\j13\helldiver\j13_1.rvmat",
            "SSV_Vanguard\textures\j13\helldiver\j13_2.rvmat",
            "SSV_Vanguard\textures\j13\helldiver\j13_3.rvmat"
        };
	};
	class SSV_Unit_Vanguard_QRF_Expeditionary: SSV_Unit_Vanguard_J13_Expeditionary
	{
		_generalMacro="SSV_Unit_Vanguard_QRF_Expeditionary";
		displayName = "Expeditionary (QRF)";
		optic="optic_Arco_blk_F";
		muzzle="";
		backpack = "WebNiX_Assault_Exo";
		linkedItems[]=
		{
			"SSV_Helmet_Vanguard_QRF_Expeditionary",
			"SSV_Vest_Vanguard_QRF_Expeditionary",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"SSV_Helmet_Vanguard_QRF_Expeditionary",
			"SSV_Vest_Vanguard_QRF_Expeditionary",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"arifle_MSBS65_black_F",
			"SSV_Weapon_Vanguard_Expeditionary_Revolver",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"arifle_MSBS65_black_F",
			"SSV_Weapon_Vanguard_Expeditionary_Revolver",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"30Rnd_65x39_caseless_msbs_mag",
			"30Rnd_65x39_caseless_msbs_mag",
			"30Rnd_65x39_caseless_msbs_mag",
			"30Rnd_65x39_caseless_msbs_mag",
			"30Rnd_65x39_caseless_msbs_mag",
			"30Rnd_65x39_caseless_msbs_mag",
			"WRS_Revolver_Magazine",
			"WRS_Revolver_Magazine",
			"SSV_Vanguard_Mag_OrganicGrenade",
			"SSV_Vanguard_Mag_EMPGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"30Rnd_65x39_caseless_msbs_mag",
			"30Rnd_65x39_caseless_msbs_mag",
			"30Rnd_65x39_caseless_msbs_mag",
			"30Rnd_65x39_caseless_msbs_mag",
			"30Rnd_65x39_caseless_msbs_mag",
			"30Rnd_65x39_caseless_msbs_mag",
			"WRS_Revolver_Magazine",
			"WRS_Revolver_Magazine",
			"SSV_Vanguard_Mag_OrganicGrenade",
			"SSV_Vanguard_Mag_EMPGrenade",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class SSV_Unit_Vanguard_Medic_Expeditionary: SSV_Unit_Vanguard_J13_Expeditionary
	{
		_generalMacro="SSV_Unit_Vanguard_Medic_Expeditionary";
		displayName = "Expeditionary (Medic)";
		optic="OPTRE_M393_EOTECH";
		muzzle="OPTRE_M6C_compensator";
		picture="pictureHeal";
		icon="iconManMedic";
		role="CombatLifeSaver";
		backpack = "OPTRE_ILCS_Rucksack_Medical";
		linkedItems[]=
		{
			"OPTRE_UNSC_CH252_Helmet2_URB_MED",
			"SSV_Vest_Vanguard_QRF_Expeditionary",
			"SSV_Mask_Vanguard_Bushi_Expeditionary",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"OPTRE_UNSC_CH252_Helmet2_URB_MED",
			"SSV_Vest_Vanguard_QRF_Expeditionary",
			"SSV_Mask_Vanguard_Bushi_Expeditionary",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"OPTRE_M7",
			"SSV_Weapon_Vanguard_Expeditionary_Revolver",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"OPTRE_M7",
			"SSV_Weapon_Vanguard_Expeditionary_Revolver",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"OPTRE_48Rnd_5x23mm_Mag",
			"OPTRE_48Rnd_5x23mm_Mag",
			"OPTRE_48Rnd_5x23mm_Mag",
			"OPTRE_48Rnd_5x23mm_Mag",
			"OPTRE_48Rnd_5x23mm_Mag",
			"OPTRE_48Rnd_5x23mm_Mag",
			"WRS_Revolver_Magazine",
			"WRS_Revolver_Magazine",
			"SSV_Vanguard_Mag_ReinforceCrate",
			"SSV_Vanguard_Mag_ReinforceCrate",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_48Rnd_5x23mm_Mag",
			"OPTRE_48Rnd_5x23mm_Mag",
			"OPTRE_48Rnd_5x23mm_Mag",
			"OPTRE_48Rnd_5x23mm_Mag",
			"OPTRE_48Rnd_5x23mm_Mag",
			"OPTRE_48Rnd_5x23mm_Mag",
			"WRS_Revolver_Magazine",
			"WRS_Revolver_Magazine",
			"SSV_Vanguard_Mag_ReinforceCrate",
			"SSV_Vanguard_Mag_ReinforceCrate",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class SSV_Unit_Vanguard_Engineer_Expeditionary: SSV_Unit_Vanguard_J13_Expeditionary
	{
		_generalMacro="SSV_Unit_Vanguard_Medic_Expeditionary";
		displayName = "Expeditionary (Engineer)";
		optic="";
		muzzle="";
		picture="pictureRepair";
		icon="iconManEngineer";
		role="Sapper";
		backpack = "Sinagami_Assault_Jetpack_Exo";
		linkedItems[]=
		{
			"OPTRE_CPD_CH251P",
			"SSV_Vest_Vanguard_SMG_Expeditionary",
			"SSV_Mask_Vanguard_Shogun_Expeditionary",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"OPTRE_CPD_CH251P",
			"SSV_Vest_Vanguard_SMG_Expeditionary",
			"SSV_Mask_Vanguard_Shogun_Expeditionary",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"OPTRE_M45TAC",
			"SSV_Weapon_Vanguard_Expeditionary_Revolver",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"OPTRE_M45TAC",
			"SSV_Weapon_Vanguard_Expeditionary_Revolver",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"WRS_Revolver_Magazine",
			"WRS_Revolver_Magazine",
			"SSV_Vanguard_Mag_ReinforceStatic",
			"SSV_Vanguard_Mag_ReinforceStatic",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Pellets",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"OPTRE_12Rnd_8Gauge_Slugs",
			"WRS_Revolver_Magazine",
			"WRS_Revolver_Magazine",
			"SSV_Vanguard_Mag_ReinforceStatic",
			"SSV_Vanguard_Mag_ReinforceStatic",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class SSV_Unit_Vanguard_Breacher_Expeditionary: SSV_Unit_Vanguard_Engineer_Expeditionary
	{
		_generalMacro="SSV_Unit_Vanguard_Medic_Expeditionary";
		displayName = "Expeditionary (Breacher)";
		optic="";
		muzzle="";
		backpack = "Ru_Assault_Exo_Grey_Light";
		linkedItems[]=
		{
			"JMSJEFF_Jeff_tac_grey_helmet",
			"Hotoke_Do_Assault_EPSM_Shoulders",
			"Balaclava_Black_EPSM",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"JMSJEFF_Jeff_tac_grey_helmet",
			"Hotoke_Do_Assault_EPSM_Shoulders",
			"Balaclava_Black_EPSM",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"OPTRE_M6B_Riot_Shield_Urban",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"OPTRE_M6B_Riot_Shield_Urban",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag",
			"OPTRE_8Rnd_127x40_Mag",
			"OPTRE_8Rnd_127x40_Mag",
			"OPTRE_8Rnd_127x40_Mag",
			"OPTRE_8Rnd_127x40_Mag",
			"OPTRE_8Rnd_127x40_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_8Rnd_127x40_Mag",
			"OPTRE_8Rnd_127x40_Mag",
			"OPTRE_8Rnd_127x40_Mag",
			"OPTRE_8Rnd_127x40_Mag",
			"OPTRE_8Rnd_127x40_Mag",
			"OPTRE_8Rnd_127x40_Mag",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class SSV_Unit_Vanguard_Sniper_Expeditionary: SSV_Unit_Vanguard_J13_Expeditionary
	{
		_generalMacro="SSV_Unit_Vanguard_Sniper_Expeditionary";
		displayName = "Expeditionary (Sniper)";
		optic="OPTRE_SRS99C_Scope";
		muzzle="";
		backpack = "Sinagami_Assault_Exo";
		linkedItems[]=
		{
			"SSV_Mask_Vanguard_Shogun_Expeditionary",
			"SSV_Vest_Vanguard_QRF_Expeditionary",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"SSV_Mask_Vanguard_Shogun_Expeditionary",
			"SSV_Vest_Vanguard_QRF_Expeditionary",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"OPTRE_SRS99C",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"OPTRE_SRS99C",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"OPTRE_4Rnd_145x114_APFSDS_Mag_D",
			"OPTRE_4Rnd_145x114_APFSDS_Mag_D",
			"OPTRE_4Rnd_145x114_APFSDS_Mag_D",
			"OPTRE_4Rnd_145x114_APFSDS_Mag_D",
			"OPTRE_4Rnd_145x114_APFSDS_Mag_D",
			"OPTRE_4Rnd_145x114_APFSDS_Mag_D",
			"SmokeShell",
			"SmokeShellGreen",
			"SSV_Vanguard_Mag_ReinforceMAC",
			"SSV_Vanguard_Mag_ReinforceMAC",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_4Rnd_145x114_APFSDS_Mag_D",
			"OPTRE_4Rnd_145x114_APFSDS_Mag_D",
			"OPTRE_4Rnd_145x114_APFSDS_Mag_D",
			"OPTRE_4Rnd_145x114_APFSDS_Mag_D",
			"OPTRE_4Rnd_145x114_APFSDS_Mag_D",
			"OPTRE_4Rnd_145x114_APFSDS_Mag_D",
			"SmokeShell",
			"SmokeShellGreen",
			"SSV_Vanguard_Mag_ReinforceMAC",
			"SSV_Vanguard_Mag_ReinforceMAC",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class SSV_Unit_Vanguard_Drone_Expeditionary: SSV_Unit_Vanguard_J13_Expeditionary
	{
		_generalMacro="SSV_Unit_Vanguard_Drone_Expeditionary";
		displayName = "Expeditionary (Drone)";
		optic="";
		muzzle="";
		backpack = "";
		linkedItems[]=
		{
			"SSV_Helmet_Vanguard_Drone_Expeditionary",
			"SSV_Vest_Vanguard_QRF_Expeditionary",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"SSV_Helmet_Vanguard_Drone",
			"SSV_Vest_Vanguard_QRF_Expeditionary",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
	};
	class SSV_Unit_Vanguard_Stealth_Expeditionary: SSV_Unit_Vanguard_J13_Expeditionary
	{
		_generalMacro="SSV_Unit_Vanguard_Stealth_Expeditionary";
		displayName="Expeditionary (Recon)";
		model="\JMSJEFF_inf\uniform_j3.p3d";
		optic = "OPTRE_SRS99C_Scope";
		muzzle = "OPTRE_MA5Suppressor";
		laser = "";
		bipod = "bipod_02_F_blk";
		backpack = "Sinagami_Assault_Exo";
		uniformClass="SSV_Uniform_Vanguard_Stealth_Expeditionary";
		linkedItems[]=
		{
			"Daemon_Full_accessories_Black",
			"SSV_Vest_Vanguard_QRF_Expeditionary",
			"Balaclava_Black_EPSM",
			"NVTG_Daemon_DS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"Daemon_Full_accessories_Black",
			"SSV_Vest_Vanguard_QRF_Expeditionary",
			"Balaclava_Black_EPSM",
			"NVTG_Daemon_DS",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio"
		};
		weapons[]=
		{
			"OPTRE_M393_DMR",
			"Throw",
			"Put",
			"Binocular"
		};
		respawnWeapons[]=
		{
			"OPTRE_M393_DMR",
			"Throw",
			"Put",
			"Binocular"
		};
		magazines[]=
		{
			"OPTRE_15Rnd_762x51_Mag",
			"OPTRE_15Rnd_762x51_Mag",
			"OPTRE_15Rnd_762x51_Mag",
			"OPTRE_15Rnd_762x51_Mag",
			"OPTRE_15Rnd_762x51_Mag",
			"OPTRE_15Rnd_762x51_Mag",
			"HandGrenade",
			"HandGrenade",
			"SSV_Vanguard_Mag_ReinforceVehicle",
			"SSV_Vanguard_Mag_ReinforceCrate",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		respawnMagazines[]=
		{
			"OPTRE_15Rnd_762x51_Mag",
			"OPTRE_15Rnd_762x51_Mag",
			"OPTRE_15Rnd_762x51_Mag",
			"OPTRE_15Rnd_762x51_Mag",
			"OPTRE_15Rnd_762x51_Mag",
			"OPTRE_15Rnd_762x51_Mag",
			"HandGrenade",
			"HandGrenade",
			"SSV_Vanguard_Mag_ReinforceVehicle",
			"SSV_Vanguard_Mag_ReinforceCrate",
			"SmokeShell",
			"SmokeShellGreen",
			"Chemlight_green",
			"Chemlight_green"
		};
		hiddenSelectionsTextures[] =
		{
			"SSV_Vanguard\textures\j13\helldiver\j3_co.paa"
		};
        hiddenSelectionsMaterials[] =
        {
            "SSV_Vanguard\textures\j13\helldiver\j3.rvmat"
        };
	};